############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 4

[[main]]
name = "Contact"
url = "/contact"
weight = 4

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "/contact"

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 3
